In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Automobile_data.csv")

In [4]:
df.head()

index      company   body-style  ...  horsepower  average-mileage    price
0      0  alfa-romero  convertible  ...         111               21  13495.0
1      1  alfa-romero  convertible  ...         111               21  16500.0
2      2  alfa-romero    hatchback  ...         154               19  16500.0
3      3         audi        sedan  ...         102               24  13950.0
4      4         audi        sedan  ...         115               18  17450.0

[5 rows x 10 columns]

# **Find the most expensive car company name**

In [5]:
df[['company','price']][df.price==df['price'].max()]

company    price
35  mercedes-benz  45400.0

# **Find each company's highest price car**

In [7]:
car_manufactures = df.groupby('company')
car_manufactures[['company','price']].max()

company    price
company                              
alfa-romero      alfa-romero  16500.0
audi                    audi  18920.0
bmw                      bmw  41315.0
chevrolet          chevrolet   6575.0
dodge                  dodge   6377.0
honda                  honda  12945.0
isuzu                  isuzu   6785.0
jaguar                jaguar  36000.0
mazda                  mazda  18344.0
mercedes-benz  mercedes-benz  45400.0
mitsubishi        mitsubishi   8189.0
nissan                nissan  13499.0
porsche              porsche  37028.0
toyota                toyota  15750.0
volkswagen        volkswagen   9995.0
volvo                  volvo  13415.0

# **Find the average mileage, horsepower of each car making company.**

In [8]:
car_manufactures[['company','horsepower','average-mileage']].mean()

horsepower  average-mileage
company                                   
alfa-romero    125.333333        20.333333
audi           109.250000        20.000000
bmw            144.833333        19.000000
chevrolet       62.666667        41.000000
dodge           68.000000        31.000000
honda           92.333333        26.333333
isuzu           72.666667        33.333333
jaguar         204.666667        14.333333
mazda           75.400000        28.000000
mercedes-benz  153.500000        18.000000
mitsubishi      78.000000        29.500000
nissan          82.800000        31.400000
porsche        234.000000        17.000000
toyota          75.428571        28.714286
volkswagen      72.250000        31.750000
volvo          114.000000        23.000000

# **Print all Nissan car details**

In [10]:
nissandf = car_manufactures.get_group('nissan')
nissandf

index company body-style  ...  horsepower  average-mileage    price
40     53  nissan      sedan  ...          55               45   7099.0
41     54  nissan      sedan  ...          69               31   6649.0
42     55  nissan      sedan  ...          69               31   6849.0
43     56  nissan      wagon  ...          69               31   7349.0
44     57  nissan      sedan  ...         152               19  13499.0

[5 rows x 10 columns]

# **Count total cars per company**

In [11]:
df['company'].value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
porsche          3
honda            3
jaguar           3
alfa-romero      3
isuzu            3
chevrolet        3
volvo            2
dodge            2
Name: company, dtype: int64

# **Sort all cars by price column**

In [12]:
df. sort_values(by=['price'])

index        company body-style  ...  horsepower  average-mileage    price
13     16      chevrolet  hatchback  ...          48               47   5151.0
27     36          mazda  hatchback  ...          68               30   5195.0
48     66         toyota  hatchback  ...          62               35   5348.0
36     49     mitsubishi  hatchback  ...          68               37   5389.0
28     37          mazda  hatchback  ...          68               31   6095.0
..    ...            ...        ...  ...         ...              ...      ...
11     14            bmw      sedan  ...         182               16  41315.0
35     47  mercedes-benz    hardtop  ...         184               14  45400.0
22     31          isuzu      sedan  ...          70               38      NaN
23     32          isuzu      sedan  ...          70               38      NaN
47     63        porsche  hatchback  ...         288               17      NaN

[61 rows x 10 columns]

Concatenate two data frames using the following conditions

GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}

JapaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

In [13]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
carsdf1 = pd.DataFrame.from_dict(GermanCars)
JapaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
carsdf2 = pd.DataFrame.from_dict(JapaneseCars)

In [15]:
carsdf = pd.concat([carsdf1, carsdf2],keys =["Germany","Japan"])
carsdf

Company   Price
Germany 0         Ford   23845
        1     Mercedes  171995
        2          BMV  135925
        3         Audi   71400
Japan   0       Toyota   29995
        1        Honda   23600
        2       Nissan   61500
        3  Mitsubishi    58900

Merge two data frames using the following condition

Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}

car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [16]:
car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
pricedf = pd.DataFrame.from_dict(car_Price)
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}
horsepowerdf = pd.DataFrame.from_dict(car_Horsepower)

In [17]:
price_horsepower = pd.merge(pricedf, horsepowerdf, on = 'Company')
price_horsepower

Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160